### ISSUE TITLE
Postgre specific

### ISSUE THREAD

**Issue by IlianIliev** [luminousmen/reset_migrations#1]
Hey,

nice tool you have there. However I see that you have hardcoded the command for deleting migrations to be postgre specific. How about using the following:

```
python manage.py dbshell < "DELETE FROM django_migrations;"
```

**Comment by luminousmen** [comment]
Yeah, thanks for reply! Didn't actually think about it :) See: https://github.com/luminousmen/reset_migrations/commit/f51c83485a548702317aa001361cf74f08ed7657
